// packages/react/src/components/Button.tsx
"use client";

import * as React from "react";
import { LoaderCircleIcon } from "lucide-react";
import { iconSlotClass, spinnerClass } from "@dept/core/recipes";
import type { ButtonBaseContract } from "@dept/core/contracts";

import { Button as ButtonBase } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export interface ButtonProps
  extends Omit<React.ComponentProps<typeof ButtonBase>, keyof ButtonBaseContract>,
    ButtonBaseContract {
  /** Icon rendered before the button text */
  leftIcon?: React.ReactNode;
  /** Icon rendered after the button text */
  rightIcon?: React.ReactNode;
}

function Button({
  className,
  children,
  isLoading = false,
  leftIcon,
  rightIcon,
  disabled,
  ...props
}: ButtonProps) {
  return (
    <ButtonBase
      className={cn(className)}
      disabled={disabled || isLoading}
      aria-busy={isLoading || undefined}
      data-loading={isLoading || undefined}
      {...props}
    >
      {isLoading ? (
        <span data-icon="inline-start" className={iconSlotClass}>
          <LoaderCircleIcon className={spinnerClass} aria-hidden />
        </span>
      ) : (
        leftIcon && (
          <span data-icon="inline-start" className={iconSlotClass}>
            {leftIcon}
          </span>
        )
      )}
      {children}
      {rightIcon && (
        <span data-icon="inline-end" className={iconSlotClass}>
          {rightIcon}
        </span>
      )}
    </ButtonBase>
  );
}

export { Button };

// packages/svelte/src/components/Button/Button.svelte
<script lang="ts" module>
  // Public Button — the stable API. Mirrors @dept/react's Button.tsx: adds
  // isLoading + leftIcon/rightIcon (here as Svelte Snippets) on top of the ui/
  // primitive. Shared prop contract + icon-slot classes come from @dept/core.
  import type { Snippet } from "svelte";
  import type { ButtonBaseContract } from "@dept/core/contracts";

  export type ButtonProps = ButtonBaseContract & {
    class?: string;
    href?: string;
    children: Snippet;
    leftIcon?: Snippet;
    rightIcon?: Snippet;
  };
</script>

<script lang="ts">
  import { LoaderCircle } from "@lucide/svelte";
  import { iconSlotClass, spinnerClass } from "@dept/core/recipes";
  import UiButton from "../ui/button.svelte";

  let {
    variant = "default",
    size = "default",
    isLoading = false,
    disabled = false,
    class: className,
    href,
    children,
    leftIcon,
    rightIcon,
    ...restProps
  }: ButtonProps = $props();
</script>

<UiButton
  {variant}
  {size}
  {href}
  class={className}
  disabled={disabled || isLoading}
  aria-busy={isLoading || undefined}
  data-loading={isLoading || undefined}
  {...restProps}
>
  {#if isLoading}
    <span data-icon="inline-start" class={iconSlotClass}>
      <LoaderCircle class={spinnerClass} aria-hidden="true" />
    </span>
  {:else if leftIcon}
    <span data-icon="inline-start" class={iconSlotClass}>
      {@render leftIcon()}
    </span>
  {/if}

  {@render children?.()}

  {#if rightIcon}
    <span data-icon="inline-end" class={iconSlotClass}>
      {@render rightIcon()}
    </span>
  {/if}
</UiButton>
